//Automatically generated by makefile, do not edit
.n64 // Let armips know we're coding for the N64 architecture
.open "rom/mp1.z64", "rom/mp1.mod.z64", 0 // Open the ROM file
.include "asm/mp1_symbols.asm"
.include "asm/patchBoot.asm"
.headersize 0x7E400000
.org 0x80400000
START:
.include "asm/crash.s"
.include "asm/hooks_new_location.s"
.importobj "obj/crash.o"
.importobj "obj/main.o"
 .align 8
 END:
.close //close file
