//Automatically generated by makefile, do not edit
.n64 // Let armips know we're coding for the N64 architecture
.open "rom/mp1-mp3.z64", "rom/mp1-mp3.mod.z64", 0 // Open the ROM file
.include "asm/mp1_symbols.asm"
.include "asm/patchBoot.asm"
.headersize 0x7E712B00
.org 0x80400000
PAYLOAD_START_RAM:
.include "asm/combo.s"
.include "asm/crash.s"
.include "asm/hooks_new_location.s"
.importobj "obj/cache.o"
.importobj "obj/crash.o"
.importobj "obj/main.o"
.importobj "obj/system.o"
 .align 8
 PAYLOAD_END_RAM:
.close //close file
